# fly.toml app configuration file generated for titanicuserapi on 2023-08-08T10:22:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanicuserapi"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
